name: CI-SFTP

# Controla cuándo se ejecutará la acción.
on:
  # Activa el workflow en eventos push o pull request pero sólo para la rama que elijas.
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # workflow_dispatch: Le permite ejecutar este workflow manualmente desde la pestaña Acciones.
  workflow_dispatch:

# Un workflow se compone de uno o varios jobs que pueden ejecutarse de forma secuencial o en paralelo.
jobs:
  # Este workflow contiene un solo job llamado "SFTP".
  deploy-via-sftp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Build page
        run: npm run build
      
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          # username: Nombre de usuario con el cual nos conectaremos al servidor.
          username: ubuntu
          # server: Nombre del servidor o IP.
          server: 54.197.249.198
          port: 22 
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

          # local_path: Ruta dentro del repositorio la cual quieres copiar en el servidor,por defecto es ./*
          local_path: ./build/*
          
          # remote_path: Ruta remota donde se copiaran los archivos del repositorio.
          remote_path: /var/www/docs.wordpress-framework.com/htdocs/
          
          # SFTP args
          args: '-o ConnectTimeout=5'
